# ----------------------------------- #
#    Package Manager Configuration    #
# ----------------------------------- #

# Make sure to enter the exact command you use as the normal user!
# That means including 'sudo' or 'doas' or whatever if the command needs it.
# Where you would put packages, enter '#:?'.

# Example: install = "sudo apt install #:?"

install = "yay -S" # Example: sudo apt install #:?
remove = "yay -R" # Example: sudo apt remove #:?
sync = "yay -Sy" # Example: sudo apt update
upgrade = "yay -Syu" # Example: sudo apt upgrade

plural_name = " coreutils cliphist cmake curl fuzzel rsync wget ripgrep gojq npm meson typescript gjs dart-sass axel aylurs-gtk-shell webp-pixbuf-loader gtk-layer-shell gtk3 gtksourceview3 gobject-introspection upower yad ydotool polkit-gnome gnome-keyring gnome-control-center blueberry networkmanager brightnessctl wlsunset gnome-bluetooth-3.0 adw-gtk3-git qt5ct qt5-wayland gradience-git fontconfig ttf-readex-pro ttf-jetbrains-mono-nerd ttf-material-symbols-variable-git ttf-space-mono-nerd fish foot starship swappy wf-recorder grim tesseract tesseract-data-eng slurp pavucontrol wireplumber libdbusmenu-gtk3 plasma-browser-integration playerctl swww python-build python-materialyoucolor-git python-pillow python-pywal python-setuptools-scm python-wheel rofi-git pfetch-git neofech-git pywal-git  "

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

# many_pkg_args = BOOL: Can you supply many packages as an argument? Example: 'sudo apt install git vim wget'

config = { many_pkg_args = true }
