# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.
pkg_managers.system.pkgs = [
    # "git",
]

# Packages to be installed via Flatpak.
pkg_managers.flatpak.pkgs = [
    # "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
pkg_managers.cargo.pkgs = [
    # "bacon",
]
