--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/personal-dots/Pictures/em-rofi.webp"

-- Special
background="#0F1827"
foreground="#c6bece"
cursor="#c6bece"

-- Colors
color0="#0F1827"
color1="#234083"
color2="#2C4B8C"
color3="#375EA7"
color4="#59669B"
color5="#8B79A4"
color6="#7189BC"
color7="#c6bece"
color8="#8a8590"
color9="#234083"
color10="#2C4B8C"
color11="#375EA7"
color12="#59669B"
color13="#8B79A4"
color14="#7189BC"
color15="#c6bece"
