# Shell variables
# Generated by 'wal'
wallpaper='/home/personal-dots/Pictures/em-rofi.webp'

# Special
background='#0F1827'
foreground='#c6bece'
cursor='#c6bece'

# Colors
color0='#0F1827'
color1='#234083'
color2='#2C4B8C'
color3='#375EA7'
color4='#59669B'
color5='#8B79A4'
color6='#7189BC'
color7='#c6bece'
color8='#8a8590'
color9='#234083'
color10='#2C4B8C'
color11='#375EA7'
color12='#59669B'
color13='#8B79A4'
color14='#7189BC'
color15='#c6bece'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
